title: "BAKELOULA EUNICE"

logo: /im/Im_Identité.jpg

description: >
  Robotics & Automation Engineer
  <br>
  Designing intelligent robotic systems for tomorrow's industry.

show_downloads: false

theme: jekyll-theme-minimal

lang: fr
